{{- range $nodeIndex := until ( $.Values.app.brokers.count | int ) }}
  {{- $portExt := ( printf $.Values.app.node.listener.external.port.printf $nodeIndex ) | int }}
  {{- $svcName := ( printf $.Values.app.node.svc.name.printf $.Release.Name ( printf "%d" $nodeIndex ) ) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $svcName }}
  labels:
    app: {{ $.Release.Name }}
    svc-type: broker
    node-index: '{{ $nodeIndex }}'
spec:
  ports:
  - name: server-ext
    port: {{ $portExt }}
  selector:
    app: {{ $.Release.Name }}
    pod-type: broker
    apps.kubernetes.io/pod-index: '{{ $nodeIndex }}'
---
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-hs
  labels:
    app: {{ $.Release.Name }}
    svc-type: headless
spec:
  ports:
  - name: server-int
    port: {{ $.Values.app.node.listener.internal.port.number | int }}
  clusterIP: None
  selector:
    app: {{ $.Release.Name }}
    pod-type: broker
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $.Release.Name }}-broker
  labels:
    app: {{ $.Release.Name }}
    statefulset-type: broker
spec:
  selector:
    matchLabels:
      app: {{ $.Release.Name }}
      pod-type: broker
  serviceName: {{ $.Release.Name }}-hs
  replicas: {{ $.Values.app.brokers.count }}
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: {{ $.Release.Name }}
        pod-type: broker
    spec:
  {{- if eq $.Values.deployment.antiAffinity "hard"}}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: "app"
                operator: In
                values:
                - {{ $.Release.Name | quote }}
              - key: "pod-type"
                operator: In
                values:
                - "node"
            topologyKey: "kubernetes.io/hostname"
  {{- else if eq $.Values.deployment.antiAffinity "soft"}}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: "app"
                  operator: In
                  values:
                  - {{ $.Release.Name | quote }}
                - key: "pod-type"
                  operator: In
                  values:
                  - "node"
              topologyKey: "kubernetes.io/hostname"
  {{- end}}
      terminationGracePeriodSeconds: {{ $.Values.app.node.terminationGracePeriodSeconds }}
      containers:
      - name: {{ $.Release.Name }}-borker
        imagePullPolicy: Always
        image: "localhost:5000/lapsatech/kubernetes-kafka_3.6:latest"
        resources:
          limits:
            memory: {{ $.Values.app.node.limits.memory | quote }}
            cpu: {{ $.Values.app.node.limits.cpu | quote }}
        ports:
        - name: server-int
          containerPort: {{ $.Values.app.node.listener.internal.port.number | int }}
#        - name: server-ext
#          containerPort: --can't evaluate in statefulset setup
        env:
        - name: NODE_INDEX
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
        - name: NODE_INT_PORT
          value: {{ $.Values.app.node.listener.internal.port.number | quote }}
        - name: NODE_EXT_NAME_PRINTF
          value: {{ printf $.Values.app.node.listener.external.name.printf $.Release.Name "%s" $.Release.Namespace | quote }}
        - name: NODE_EXT_PORT_PRINTF
          value: {{ $.Values.app.node.listener.external.port.printf | quote }}
        - name: DATA_DIR
          value: "{{ $.Values.app.node.storage.mountPath }}/data"
        - name: LOCAL_LOGS_DIR
          value: "/tmp/logs"
        - name: MEMORY_HEAP
          value: {{ $.Values.app.kafka.heap | quote }}
        - name: LOG_LEVEL
          value: INFO
        - name: "ZOOKEEPER_CONNECT"
          value: "{{ $.Values.zk.svc.host }}:{{ $.Values.zk.svc.port }}/kafka/{{ $.Release.Name }}"
  {{- range $k, $v := $.Values.app.kafka.overrides }}
        - name: "OVERRIDE_{{ $k }}"
          value: {{ $v | quote }}
  {{- end }}
  {{- if $.Values.deployment.probes.readiness.enabled }}
        readinessProbe:
          exec:
            command:
            - kafka-ready.sh
          failureThreshold: 10
          initialDelaySeconds: 10
          periodSeconds: 60
          timeoutSeconds: 30
  {{- end }}
  {{- if $.Values.deployment.probes.liveness.enabled }}
        livenessProbe:
          exec:
            command:
            - kafka-ready.sh
          failureThreshold: 10
          initialDelaySeconds: 120
          periodSeconds: 120
          timeoutSeconds: 30
  {{- end }}
        volumeMounts:
        - name: data
          mountPath: {{ $.Values.app.node.storage.mountPath | quote }}
        - name: templogs
          mountPath: /tmp/logs
      volumes:
      - name: templogs
        emptyDir: {}
  {{- if not $.Values.deployment.pvc.enabled }}
      - name: data
        emptyDir: {}
  {{- end }}
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
  {{- if $.Values.deployment.pvc.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: data
    labels:
      app: {{ $.Release.Name }}
      pvc-type: broker-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: "100Mi"
  {{- end }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $.Release.Name }}-broker-pdb
  labels:
    app: {{ $.Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ $.Release.Name }}
      pod-type: broker
  maxUnavailable: {{ $.Values.app.brokers.maxUnavailable }}
